require 'opium/extensions/object'
require 'opium/extensions/string'
require 'opium/extensions/numeric'
require 'opium/extensions/float'
require 'opium/extensions/integer'
require 'opium/extensions/boolean'
require 'opium/extensions/true_class'
require 'opium/extensions/false_class'