language: ruby
cache: bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - 2.2.0
  
script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - joshua.bowers+code@gmail.com
    on_failure: change
    on_success: never